### ISSUE TITLE
Error in predict_disorder_uniprot for some uniprot ids

### ISSUE THREAD

**Issue by keithchev** [idptools/metapredict#1]
For some uniprot ids, `metapredict.predict_disorder_uniprot` throws a ValueError with the message 
```
ValueError: Invalid amino acid detected: ". 
```
Examples: O95861, P22087, P35606.

This appears to occur when the protein description in the fasta file retrieved from Uniprot contains a single apostrophe. This breaks the string manipulation in `metadata.backend.uniprot_predictions.fetch_sequence`, resulting in its appending a double-quote character to the protein sequence it returns. I think this could be fixed by changing this line in `fetch_sequence`:
```python
s = "".join(str(r.data).split('\\n')[1:]).replace("'", "")
```

to this:
```python
s = ''.join(r.data.decode().split('\n')[1:])
```

**Comment by ryanemenecker** [comment]
Sorry for the delay in my response, and thank you for reporting the issue (as well as a potential solution!!)! I will look into fixing this today and push an update within the next 48 hours addressing this error.

Thank you again!
Ryan Emenecker
The Holehouse Lab

**Comment by ryanemenecker** [comment]
I just pushed an update that fixes the issue. I tested all 3 examples you provided and everything seems to have worked. Please let me know if the issue persists or if you identify any new issues!

I also updated the pypi package, so if you run
`pip install metapredict --upgrade`
then it should update metapredict to V1.5 (which fixes your issue).

Thanks again for letting us know there was an issue!
Ryan Emenecker
Holehouse Lab
