### ISSUE TITLE
Error in pip intall metapredict

### ISSUE THREAD

**Issue by mmkar5** [idptools/metapredict#14]
For python version 3.12.1
Collecting metapredict
  Using cached metapredict-2.62.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      C:\Users\AppData\Local\Temp\pip-install-btetpe6o\metapredict_97d618a69661457f8a9b51e9a68e3525\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      ########################################
      
      Error: Please install cython first:
      
      pip install cython
      
      ########################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by alexholehouse** [comment]
Hi there!

As suggested by the error message, you need to install cython first - specifically if you first run:

    pip install cython

and then re-run

    pip install metapredict

this should now work, but let me know if not!

**Comment by alexholehouse** [comment]
ALTHOUGH, actually I think you will run into issues because right now metapredict requires Python 3.11 or lower in part due to various downstream dependencies on other things, so you may need to setup a Python 3.11 environment for this to run!

**Comment by mmkar5** [comment]
I did install Cython but still, it was not working. So, I think I will need to use a Python 3.11 environment.
