### ISSUE TITLE
request: py3.12 compatibility

### ISSUE THREAD

**Issue by h-ahl** [idptools/metapredict#16]
Thanks for a great package!

Setup states: `python_requires=">=3.5,<3.12.0"`

Would be helpful if the package could be made compatible with the latest python version, 3.12. (NB: py3.13 release date 1 October)

**Comment by ryanemenecker** [comment]
Hi h-ahl,

Thanks for the request! We are working on some updates to metapredict at the moment including py3.12 compatibility. We're hoping to get the update out soon.

Ryan

**Comment by alexholehouse** [comment]
@h-ahl - just to let you know we merged in your pull request and added versioningit support; all builds right and all tests passing. We also did the same for protfasta (a required dependency), and have pull requests in for getSequence and alphaPredict (two dependencies we have). So we are very close to having everything be sorted for 3.12 compliance. Thanks again so much for your help.

**Comment by alexholehouse** [comment]
So, nearly there, but keeping this open until the full stack can build on 3.12...

**Comment by ryanemenecker** [comment]
Thank you to alexholehouse who got this working! Newest version (2.65.0) on PyPi is no longer restricted to below 3.12.

**Comment by h-ahl** [comment]
Many thanks to all! Your hard work is much appreciated 🎉🥳
