### ISSUE TITLE
Add channel and python version restrictions to the dependency install command

### ISSUE THREAD

**Issue by NilaBlueshirt** [idptools/metapredict#18]
Hello metapredict developers, 

Thanks for your great efforts! I recently helped a user installed metapredict, and found that a small change to the dependency install command in the README.md would make the process easier:

conda install -c conda-forge -c pytorch python=3.11 numpy pytorch scipy cython matplotlib

Regards,
Nil

**Comment by alexholehouse** [comment]
Nil - you are _absolutely_ right and we should have done this; GREAT suggestion, I just updated our readme and we'll propagate it into the docs (and, fix the 3.12 compatibility issue :-/). Thanks for the great suggestion!

**Comment by NilaBlueshirt** [comment]
You are very welcome!
