### ISSUE TITLE
R2 value

### ISSUE THREAD

**Issue by dukeshan2009** [idptools/metapredict#7]
Hi, there. 

This is Xingjian. From University of Kentucky. My email is xsh230@uky.edu
I am testing Metapredict pLDDT vs Alphafold2 pLDDT. I could verify your result in the paper for the sup35 protein. But when I used the same code to test on 1 million protien. I got pretty bad results. Lots of r2 results are lower than 0 which means metapredict gives really bad pLDDT results vs AF2's. I even test one group that might be your training data. the results are still pretty bad. 
I am wondering how you pull out the pLDDT score by Metapredict. And how you get the r2 value. 
I can share my code that i used to test the your modle.

**Comment by ryanemenecker** [comment]
Hi Xingjian,
I would be interested to see your code to see if I can help you out. Feel free to send me an email at remenecker@wustl.edu if it would be easier to carry out further correspondence over email.
Best,
Ryan Emenecker

**Comment by dukeshan2009** [comment]
Hi, Ryan.  Thanks for replay so fast. I am summarizing my codes and results. Making it as clear as possible. Should be in a minute.  Thank you for your patient.  Best, Xingjian   From: Ryan EmeneckerSent: Wednesday, April 12, 2023 11:24 AMTo: idptools/metapredictCc: dukeshan2009; AuthorSubject: Re: [idptools/metapredict] R2 value (Issue #7) Hi Xingjian,I would be interested to see your code to see if I can help you out. Feel free to send me an email at ***@***.*** if it would be easier to carry out further correspondence over email.Best,Ryan Emenecker—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dukeshan2009** [comment]
Hi, Ryan.  The following link is my metapredict testing GitHub link. https://github.com/dukeshan2009/Metapredict.git Please check. If there is any misunderstanding, please let me know.   Best,  Xingjian From: GmailSent: Wednesday, April 12, 2023 11:26 AMTo: idptools/metapredict; idptools/metapredictCc: AuthorSubject: RE: [idptools/metapredict] R2 value (Issue #7) Hi, Ryan.  Thanks for replay so fast. I am summarizing my codes and results. Making it as clear as possible. Should be in a minute.  Thank you for your patient.  Best, Xingjian   From: Ryan EmeneckerSent: Wednesday, April 12, 2023 11:24 AMTo: idptools/metapredictCc: dukeshan2009; AuthorSubject: Re: [idptools/metapredict] R2 value (Issue #7) Hi Xingjian,I would be interested to see your code to see if I can help you out. Feel free to send me an email at ***@***.*** if it would be easier to carry out further correspondence over email.Best,Ryan Emenecker—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ryanemenecker** [comment]
Final comment - 
Thank you for the feedback Xingjian. The pLDDT score predictions using metapredict are on average fairly accurate. However, if you predict many sequences (for example, a million) and examine the individual R2 _per sequence_, you will find examples where metapredict does a very bad job predicting the pLDDT scores (R2 close to 0) and examples where metapredict does a great job (R2 close to 1). _On average_ metapredict will have a value close to an R2 of ~0.85. Nonetheless, given enough sequences, finding examples of R2 values for individual sequences with very low or very high R2 values is expected.
